export const mockCandidates = [
  {
    id: "1",
    name: "Dr. Sarah Chen",
    email: "sarah.chen@stanford.edu",
    phone: "+1 (650) 555-0123",
    university: "Stanford University",
    department: "Computer Science",
    graduationYear: 2024,
    yearsExperience: 4,
    skills: ["Machine Learning", "Deep Learning", "Computer Vision", "PyTorch", "TensorFlow", "Python", "CUDA"],
    researchAreas: ["Computer Vision", "Generative AI", "Multimodal Learning"],
    publications: [
      {
        title: "Efficient Vision Transformers for Real-time Object Detection",
        conference: "NeurIPS 2023",
        year: 2023,
        citations: 127,
        url: "https://example.com/paper1",
      },
      {
        title: "Self-Supervised Learning for Medical Image Analysis",
        conference: "ICML 2023",
        year: 2023,
        citations: 89,
        url: "https://example.com/paper2",
      },
      {
        title: "Attention Mechanisms in Multi-Modal Fusion",
        conference: "ICLR 2022",
        year: 2022,
        citations: 203,
        url: "https://example.com/paper3",
      },
    ],
    internships: [
      {
        company: "Google Research",
        role: "Research Intern",
        duration: "3 months",
        year: 2023,
      },
      {
        company: "Meta AI",
        role: "ML Research Intern",
        duration: "4 months",
        year: 2022,
      },
    ],
  },
  {
    id: "2",
    name: "Alex Rodriguez",
    email: "alex.rodriguez@mit.edu",
    phone: "+1 (617) 555-0456",
    university: "MIT",
    department: "Electrical Engineering and Computer Science",
    graduationYear: 2024,
    yearsExperience: 5,
    skills: [
      "Systems Architecture",
      "Distributed Systems",
      "Performance Optimization",
      "C++",
      "Rust",
      "Go",
      "Kubernetes",
    ],
    researchAreas: ["Computer Systems", "Operating Systems", "Distributed Computing"],
    publications: [
      {
        title: "Scalable Memory Management in Modern Operating Systems",
        conference: "ASPLOS 2023",
        year: 2023,
        citations: 156,
        url: "https://example.com/paper4",
      },
      {
        title: "High-Performance Networking for Cloud Computing",
        conference: "SIGCOMM 2023",
        year: 2023,
        citations: 98,
        url: "https://example.com/paper5",
      },
      {
        title: "Container Orchestration at Scale",
        conference: "OSDI 2022",
        year: 2022,
        citations: 234,
        url: "https://example.com/paper6",
      },
    ],
    internships: [
      {
        company: "Microsoft Research",
        role: "Systems Research Intern",
        duration: "4 months",
        year: 2023,
      },
      {
        company: "Amazon Web Services",
        role: "Principal Engineer Intern",
        duration: "3 months",
        year: 2022,
      },
    ],
  },
  {
    id: "3",
    name: "Dr. Priya Patel",
    email: "priya.patel@cmu.edu",
    university: "Carnegie Mellon University",
    department: "Machine Learning Department",
    graduationYear: 2024,
    yearsExperience: 3,
    skills: [
      "Quantum Computing",
      "Quantum Machine Learning",
      "Optimization",
      "Python",
      "Qiskit",
      "Cirq",
      "Mathematics",
    ],
    researchAreas: ["Quantum Computing", "Quantum Algorithms", "Quantum Machine Learning"],
    publications: [
      {
        title: "Quantum Advantage in Machine Learning Tasks",
        conference: "Nature Quantum Information",
        year: 2023,
        citations: 312,
        url: "https://example.com/paper7",
      },
      {
        title: "Variational Quantum Algorithms for Optimization",
        conference: "Physical Review A",
        year: 2023,
        citations: 178,
        url: "https://example.com/paper8",
      },
      {
        title: "Noise-Resilient Quantum Machine Learning",
        conference: "Quantum Science and Technology",
        year: 2022,
        citations: 145,
        url: "https://example.com/paper9",
      },
    ],
    internships: [
      {
        company: "IBM Quantum",
        role: "Quantum Research Intern",
        duration: "6 months",
        year: 2023,
      },
      {
        company: "Google Quantum AI",
        role: "Research Intern",
        duration: "3 months",
        year: 2022,
      },
    ],
  },
  {
    id: "4",
    name: "Michael Zhang",
    email: "michael.zhang@berkeley.edu",
    university: "UC Berkeley",
    department: "Computer Science",
    graduationYear: 2025,
    yearsExperience: 3,
    skills: [
      "Natural Language Processing",
      "Large Language Models",
      "Transformers",
      "PyTorch",
      "Hugging Face",
      "Python",
      "CUDA",
    ],
    researchAreas: ["Natural Language Processing", "Large Language Models", "AI Safety"],
    publications: [
      {
        title: "Efficient Training of Large Language Models",
        conference: "NeurIPS 2023",
        year: 2023,
        citations: 89,
        url: "https://example.com/paper10",
      },
      {
        title: "Bias Detection in Language Models",
        conference: "ACL 2023",
        year: 2023,
        citations: 67,
        url: "https://example.com/paper11",
      },
    ],
    internships: [
      {
        company: "OpenAI",
        role: "Research Intern",
        duration: "4 months",
        year: 2023,
      },
    ],
  },
  {
    id: "5",
    name: "Dr. Emily Johnson",
    email: "emily.johnson@caltech.edu",
    university: "Caltech",
    department: "Computing and Mathematical Sciences",
    graduationYear: 2024,
    yearsExperience: 4,
    skills: ["Robotics", "Computer Vision", "Control Systems", "ROS", "Python", "C++", "MATLAB"],
    researchAreas: ["Robotics", "Autonomous Systems", "Human-Robot Interaction"],
    publications: [
      {
        title: "Learning Dexterous Manipulation from Human Demonstrations",
        conference: "ICRA 2023",
        year: 2023,
        citations: 134,
        url: "https://example.com/paper12",
      },
      {
        title: "Safe Reinforcement Learning for Robotic Systems",
        conference: "RSS 2023",
        year: 2023,
        citations: 78,
        url: "https://example.com/paper13",
      },
      {
        title: "Multi-Agent Coordination in Autonomous Vehicles",
        conference: "IROS 2022",
        year: 2022,
        citations: 156,
        url: "https://example.com/paper14",
      },
    ],
    internships: [
      {
        company: "Tesla Autopilot",
        role: "Robotics Engineer Intern",
        duration: "5 months",
        year: 2023,
      },
      {
        company: "Boston Dynamics",
        role: "Research Intern",
        duration: "3 months",
        year: 2022,
      },
    ],
  },
]
